allowBuilds:
  sharp: true
  unrs-resolver: true
  "@prisma/client": true
  "@prisma/engines": true
  prisma: true
  esbuild: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
packages:
  - frontend
  - backend
